# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

jobs:
  - job: RunAzqr
    displayName: 'Install Azure Quick Review'
    steps:
    - script: |
        latest_azqr=$(curl -sL https://api.github.com/repos/Azure/azqr/releases/latest | jq -r ".tag_name" | cut -c1-)

  - job: ScanAzqr
    displayName: 'Run Azure Quick Review'
    steps:
    - script: |
        azqr scan